version: 2
updates:
    # Update Python packages
    - package-ecosystem: "uv"
      target-branch: "develop"
      directory: "/"
      schedule:
          interval: "weekly"
      open-pull-requests-limit: 10

    # Update GitHub Actions
    - package-ecosystem: "github-actions"
      directory: "/"
      target-branch: "develop"
      schedule:
          interval: "weekly"
      open-pull-requests-limit: 10

    # Update Docker base images
    - package-ecosystem: "docker"
      directory: "/"
      target-branch: "develop"
      schedule:
          interval: "weekly"
      open-pull-requests-limit: 10
